2022-08-29 17:23:27,646 INFO werkzeug MainThread :  * Running on all addresses (0.0.0.0)
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://127.0.0.1:5000
 * Running on http://10.10.10.235:5000 (Press CTRL+C to quit)
2022-08-29 17:23:29,934 INFO root Thread-1 : Get connection to ('10.100.151.128', 9669)
2022-08-29 17:23:29,953 INFO root Thread-1 : LOOKUP ON ServiceTemplateDefinition  
2022-08-29 17:23:29,954 ERROR app Thread-1 : Exception on /cluster_names [GET]
Traceback (most recent call last):
  File "/home/dmitrytulin/PycharmProjects/API_COURSE/venv/lib/python3.9/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/dmitrytulin/PycharmProjects/API_COURSE/venv/lib/python3.9/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/dmitrytulin/PycharmProjects/API_COURSE/venv/lib/python3.9/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/dmitrytulin/PycharmProjects/API_COURSE/venv/lib/python3.9/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/dmitrytulin/PycharmProjects/API_COURSE/app/views.py", line 66, in cluster_names
    return make_response(message, status=200)
TypeError: make_response() got an unexpected keyword argument 'status'
2022-08-29 17:23:29,956 INFO werkzeug Thread-1 : 127.0.0.1 - - [29/Aug/2022 17:23:29] "[35m[1mGET /cluster_names HTTP/1.1[0m" 500 -
2022-08-29 17:23:38,274 INFO werkzeug MainThread :  * Running on all addresses (0.0.0.0)
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://127.0.0.1:5000
 * Running on http://10.10.10.235:5000 (Press CTRL+C to quit)
